config/routes.rb
Rails.application.routes.draw do
  resources :communities
  devise_for :users
  root to: 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to(
    :user,
    class_name: 'User',
    foreign_key: 'user_id',
    inverse_of: :communities
  )
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  has_many(
    :communities,
    class_name: 'Community',
    foreign_key: 'user_id',
    inverse_of: :user,
    dependent: :destroy
  )
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /communities or /communities.json
  def index
    @communities = Community.all
  end

  # GET /communities/1 or /communities/1.json
  def show
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities or /communities.json
  def create
    @community = current_user.communities.new(community_params)
    respond_to do |format|
      if @community.save
        format.html { redirect_to community_url(@community), notice: "Community was successfully created." }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1 or /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to community_url(@community), notice: "Community was successfully updated." }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1 or /communities/1.json
  def destroy
    @community.destroy

    respond_to do |format|
      format.html { redirect_to communities_url, notice: "Community was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def community_params
      params.require(:community).permit(:name, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/communities/_community.html.erb
<div id="<%= dom_id community %>">
  <p>
    <strong>Name:</strong>
    <%= community.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= community.description %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= User.find_by(id:community.user_id).email %>
  </p>

</div>

app/views/communities/_form.html.erb
<%= form_with(model: community) do |form| %>
  <% if community.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
        <% community.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/communities/edit.html.erb
<h1>Editing community</h1>

<%= render "form", community: @community %>

<br>

<div>
  <%= link_to "Show this community", @community %> |
  <%= link_to "Back to communities", communities_path %>
</div>

app/views/communities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Communities</h1>

<div id="communities">
  <% @communities.each do |community| %>
    <%= render community %>
    <p>
      <%= link_to "Show this community", community %>
    </p>
  <% end %>
</div>

<%= link_to "New community", new_community_path %>

app/views/communities/new.html.erb
<h1>New community</h1>

<%= render "form", community: @community %>

<br>

<div>
  <%= link_to "Back to communities", communities_path %>
</div>

app/views/communities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @community %>

<div>
  <%= link_to "Edit this community", edit_community_path(@community) %> |
  <%= link_to "Back to communities", communities_path %>

  <%= button_to "Destroy this community", @community, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForumApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" href="/">CommUnity</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/communities">Communities</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>

    <footer>
      <div class="container">
        CommUnity <%= Time.now.year %>
      </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to CommUnity</h1>